version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass


  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass


  node:
    image: node:latest
    user: node
    working_dir: /home/node/app
    ports:
      - '9999:9999'
    environment:
      - NODE_ENV=production
    volumes:
      - ./gate-simulator:/home/node/app
    command: npm start